domain_path: /home/was/code/FreeRTOS_Container/platform/zynqmp_fsbl/zynqmp_fsbl_bsp
app_src_dir: /home/was/App/Xilinx/2025.2/Vitis/data/embeddedsw/lib/sw_apps/zynqmp_fsbl
template: zynqmp_fsbl
lang: c
